# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
   
    # ユーザー情報取得方法
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        #Securityで使用したが、Bundleでは邪魔になるためコメントに
        # in_memory:
        #     memory:
        #         users:
        #             user:
        #                 password: $2y$12$PSTzod6.0V3iTBLwFaWr0Oxt3mAEwzCUPMmChcogjZx6yii9eQ0vq
        #                 roles: 'ROLE_USER'
        #             admin:
        #                 password: $2y$12$cE.z9hXUWJmBgzWD9dO9YecZLkul3JcbmHXVXQ1QknFGqdaWUulle
        #                 roles: 'ROLE_ADMIN'
        

    # 認証方法
    # disables authentication for assets and the profiler, adapt it according to your needs
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # フォームログイン
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: ~

            # activate different ways to authenticate
            #  logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
             
             
    
    # アクセス制御
    access_control:
        - { path: ^/unsei, roles: ROLE_ADMIN }

    
    # パスワード暗号化方法
    encoders:
        FOS\UserBundle\Model\UserInterface: argon2i  # bcrypt
    #     #Securityで使用したが、邪魔なためコメントに
    #     # Symfony\Component\Security\Core\User\User: 
    #     #     algorithm: bcrypt
    #     #     cost: 12

